### ISSUE TITLE
Can't reproduce the "classic" taproot receive address

### ISSUE THREAD

**Issue by kdmukai** [louisinger/silentium#7]
Tried to import the "classic" taproot wallet from Silentium into other wallet software.

* copy wallet's 12 words
* enter them into Sparrow, [SeedTool](https://bitcoiner.guide/seed), or SeedSigner as a taproot single sig wallet.
* Compare the first receive addr (m/86'/0'/0'/0/0) **<--- DOES NOT MATCH**

Tried with both a testnet wallet and with mainnet. Tried with new mnemonics created by Silentium and by restoring from external mnemonics created elsewhere.

What am I missing? The p2tr receive address generation looks straightforward enough in the code, but I haven't followed it all the way through all the dependencies.

**Comment by louisinger** [comment]
nice catch ! thanks for checking. I tested myself using a sparrow wallet. **keys are the same** but the taproot address is wrong (should tweak the public key). 

- silent addresses are not affected 
- working on a fix

**Comment by louisinger** [comment]
ce2494b62d4ce8da3a3f100c74621c16d2fda830 should fix. Now I get the same address using a Sparrow seed. Can you retry ?

**Comment by kdmukai** [comment]
Success! Matching "classic" receive addr confirmed.

New wallets match as expected and seem to complete sync (well, they report "No new blocks to scan"). But existing wallet / external mnemonics fire errors as described in #8.
